tools:
    external_code_coverage:
        timeout: 300
build:
    environment:
        php:
          version: 8.2.15
          compile_options: '--with-config-file-path=/home/scrutinizer/.phpenv/versions/8.2.15/etc --with-config-file-scan-dir=/home/scrutinizer/.phpenv/versions/8.2.15/etc/conf.d --prefix=/home/scrutinizer/.phpenv/versions/8.2.15 --libexecdir=/home/scrutinizer/.phpenv/versions/8.2.15/libexec --enable-intl --with-openssl --with-gd --enable-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-exif --with-libzip --with-zlib --with-zlib-dir=/usr --with-sodium --with-pdo-sqlite --enable-soap --enable-xmlreader --with-xsl --enable-ftp --with-tidy --with-xmlrpc --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --enable-pcntl --with-readline --enable-mbstring --with-curl --with-pgsql --with-pdo-pgsql --with-gettext --enable-sockets --with-bz2 --enable-bcmath --enable-calendar --with-libdir=lib --enable-fpm --enable-zts --with-gmp --with-kerberos --with-imap --with-imap-ssl --with-apxs2=/usr/bin/apxs --with-ldap --with-pear=/home/scrutinizer/.phpenv/versions/8.2.15/pear'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
