tools:
    external_code_coverage:
        timeout: 300
build:
    nodes:            
        analysis:
            commands:
                - before_commands:
                    - sudo apt-get update
                    - sudo apt-get install -y openssl libssl-dev
                    - sudo apt-get install -y php8.1-gd
            tests:
                override:
                    - php-scrutinizer-run
